# backend/pbi_template.py
# Professional Power BI Template Generator
# Generates .pbit file with 3 pages:
#   Page 1: Executive Dashboard (KPIs + Charts + Slicers)
#   Page 2: Detailed Analysis (Scatter, Matrix, Waterfall, Funnel)
#   Page 3: DAX Measures Reference

import json
import zipfile
import io


def generate_professional_pbit(
    table_name  : str,
    columns     : list,
    dax_measures: list,
    chart_type  : str = "bar"
) -> bytes:

    theme = {
        "name": "AI Analyst Theme",
        "dataColors": [
            "#2563EB","#7C3AED","#059669",
            "#DC2626","#D97706","#0891B2",
            "#BE185D","#065F46"
        ],
        "background" : "#F8FAFC",
        "foreground" : "#1E293B",
        "tableAccent": "#2563EB"
    }

    dax_reference_text = (
        "DAX MEASURES REFERENCE\n\n" +
        "\n\n".join([
            f"[{i+1}] {m['name']}\n{m['dax']}"
            for i, m in enumerate(dax_measures)
        ])
    )

    report_layout = {
        "id": 1,
        "sections": [
            {
                "id"         : 1,
                "name"       : "ExecutiveDashboard",
                "displayName": "Executive Dashboard",
                "width"      : 1280,
                "height"     : 900,
                "visualContainers": [
                    {"id":"hdr","x":0,"y":0,"width":1280,"height":60,
                     "config":json.dumps({"type":"shape","fill":"#1E293B","text":"AI Data Analyst — Executive Dashboard","fontSize":20,"fontColor":"#FFFFFF"})},
                    {"id":"sub","x":0,"y":60,"width":1280,"height":30,
                     "config":json.dumps({"type":"shape","fill":"#2563EB","text":"Generated by AI Data Analyst Tool | Powered by Llama 3.2","fontSize":11,"fontColor":"#FFFFFF"})},
                    {"id":"kpi1","x":10,"y":100,"width":230,"height":100,
                     "config":json.dumps({"type":"card","title":"Total Value","instruction":f"SUM({table_name}[value_column])"})},
                    {"id":"kpi2","x":250,"y":100,"width":230,"height":100,
                     "config":json.dumps({"type":"card","title":"Total Count","instruction":f"COUNT({table_name}[id])"})},
                    {"id":"kpi3","x":490,"y":100,"width":230,"height":100,
                     "config":json.dumps({"type":"card","title":"Average","instruction":"AVERAGE measure"})},
                    {"id":"kpi4","x":730,"y":100,"width":230,"height":100,
                     "config":json.dumps({"type":"card","title":"Growth %","instruction":"Growth measure"})},
                    {"id":"kpi5","x":970,"y":100,"width":300,"height":100,
                     "config":json.dumps({"type":"card","title":"Top Performer","fill":"#2563EB","fontColor":"#FFFFFF","instruction":"Top N measure"})},
                    {"id":"line","x":10,"y":210,"width":780,"height":320,
                     "config":json.dumps({"type":"lineChart","title":"Trend Over Time","instruction":"X: date | Y: measure"})},
                    {"id":"donut","x":800,"y":210,"width":470,"height":320,
                     "config":json.dumps({"type":"donutChart","title":"Category Breakdown","instruction":"Legend: category | Values: measure"})},
                    {"id":"bar","x":10,"y":540,"width":500,"height":280,
                     "config":json.dumps({"type":"barChart","title":"Top N Comparison","instruction":"Y: category | X: measure | Sort DESC"})},
                    {"id":"table","x":520,"y":540,"width":750,"height":280,
                     "config":json.dumps({"type":"tableEx","title":"Detailed Data","instruction":"Add all columns for detailed view"})},
                    {"id":"sl1","x":10,"y":830,"width":380,"height":60,
                     "config":json.dumps({"type":"slicer","title":"Date Range","slicerType":"dateRange","instruction":"date column"})},
                    {"id":"sl2","x":400,"y":830,"width":380,"height":60,
                     "config":json.dumps({"type":"slicer","title":"Category","slicerType":"list","instruction":"category column"})},
                    {"id":"sl3","x":790,"y":830,"width":480,"height":60,
                     "config":json.dumps({"type":"slicer","title":"Region / Dept","slicerType":"dropdown","instruction":"region column"})}
                ]
            },
            {
                "id"         : 2,
                "name"       : "DetailedAnalysis",
                "displayName": "Detailed Analysis",
                "width"      : 1280,
                "height"     : 900,
                "visualContainers": [
                    {"id":"hdr2","x":0,"y":0,"width":1280,"height":60,
                     "config":json.dumps({"type":"shape","fill":"#1E293B","text":"Detailed Analysis","fontSize":20,"fontColor":"#FFFFFF"})},
                    {"id":"scatter","x":10,"y":70,"width":600,"height":380,
                     "config":json.dumps({"type":"scatterChart","title":"Correlation Analysis","instruction":"X: measure1 | Y: measure2 | Size: measure3"})},
                    {"id":"matrix","x":620,"y":70,"width":650,"height":380,
                     "config":json.dumps({"type":"matrix","title":"Cross-tab Matrix","instruction":"Rows: category | Cols: time | Values: measure"})},
                    {"id":"waterfall","x":10,"y":460,"width":600,"height":340,
                     "config":json.dumps({"type":"waterfallChart","title":"Variance Analysis","instruction":"Category: periods | Y: change"})},
                    {"id":"funnel","x":620,"y":460,"width":650,"height":340,
                     "config":json.dumps({"type":"funnelChart","title":"Pipeline Analysis","instruction":"Group: stage | Values: count"})}
                ]
            },
            {
                "id"         : 3,
                "name"       : "DAXReference",
                "displayName": "DAX Measures Reference",
                "width"      : 1280,
                "height"     : 900,
                "visualContainers": [
                    {"id":"dax_ref","x":0,"y":0,"width":1280,"height":900,
                     "config":json.dumps({
                         "type"      : "textbox",
                         "content"   : dax_reference_text,
                         "fontSize"  : 14,
                         "fontFamily": "Courier New",
                         "background": "#1E293B",
                         "fontColor" : "#F2C811"
                     })}
                ]
            }
        ]
    }

    data_model = {
        "name"  : "AI Analyst Model",
        "tables": [{
            "name"    : table_name,
            "columns" : [{"name":c,"dataType":"string"} for c in columns],
            "measures": [
                {"name":m["name"],"expression":m["dax"]}
                for m in dax_measures
            ]
        }]
    }

    readme = f"""
╔══════════════════════════════════════════════════╗
║     AI DATA ANALYST — POWER BI TEMPLATE          ║
║         Professional Enterprise Edition           ║
╚══════════════════════════════════════════════════╝

PAGES IN THIS TEMPLATE:
═══════════════════════
Page 1: Executive Dashboard
  ├── 5 KPI Cards
  ├── Line Chart (Trend)
  ├── Donut Chart (Distribution)
  ├── Bar Chart (Top N)
  ├── Data Table
  └── 3 Slicers (Date / Category / Region)

Page 2: Detailed Analysis
  ├── Scatter Plot (Correlation)
  ├── Matrix (Cross-tab)
  ├── Waterfall (Variance)
  └── Funnel (Pipeline)

Page 3: DAX Measures Reference
  └── All AI-generated measures

HOW TO USE:
═══════════
1. Open AI_Dashboard.pbit in Power BI Desktop
2. Get Data → Text/CSV → select your file
   OR Get Data → PostgreSQL → localhost:5432/chinook
3. Rename table to: {table_name}
4. Go to Page 3 to copy your DAX measures
5. Modeling → New Measure → paste each DAX
6. Drag measures onto visuals

YOUR COLUMNS: {', '.join(columns)}

DAX MEASURES INCLUDED: {len(dax_measures)}
{chr(10).join([f"  [{i+1}] {m['name']}" for i,m in enumerate(dax_measures)])}

Built with: AI Data Analyst Tool
LLM: Llama 3.2 (Local via Ollama)
Database: PostgreSQL
"""

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("DataModel",          json.dumps(data_model,   indent=2))
        zf.writestr("Report/Layout",      json.dumps(report_layout,indent=2))
        zf.writestr("SecurityBindings",   "")
        zf.writestr("Settings",           json.dumps({"version":"1.0"}))
        zf.writestr("Version",            "5.0")
        zf.writestr("README.txt",         readme)
        zf.writestr("Theme.json",         json.dumps(theme, indent=2))
        zf.writestr("Report/StaticResources/RegisteredResources", "[]")
    buf.seek(0)
    return buf.getvalue()